### ISSUE TITLE
Bad feedback

### ISSUE THREAD

**Issue by nmaxcom** [yeoman/yo#273]
I wrote this issue a few weeks ago: https://github.com/yeoman/yo/issues/251

It was unilaterally closed, but I think that's a big mistake. The mistake being that it's okay that a piece of software let users confused about their requests.

The fact that the staff see as okay that **"Yeoman just quits when trying to use bootstrap generator"** without any notification or clue of what's going on in the background or what should I wait for etc... Is an acute case of "nearsightedness". This is a 0 on **user experience** (yup, that thing called UX) and it's something that should be addressed.

I don't care if you think I'm a pain in the neck: this isn't okay. This is something to be fixed.

**Comment by stephenplusplus** [comment]
Sorry you felt the UX from the generator was poor and that the issue was closed before a mutual resolution. We will try to be more patient before hitting the "Close" button going forward. Your feedback is always welcome, sorry we made you feel otherwise.

Let's keep the discussion of how to improve the other generator in that issue you referenced. I agree with your point, and probably a simple message explaining what happened when it ran will suffice.

Closing this for now, but feel free to re-open if you have other thoughts and ideas that are relevant to improving "yo" as a whole.

**Comment by nmaxcom** [comment]
Thank you very much and congrats for a good adaptation.
