### ISSUE TITLE
yo doesn't find any generators installed globally with nvm + iojs

### ISSUE THREAD

**Issue by oriSomething** [yeoman/yo#291]
nvm v0.23.3
npm v2.4.1
iojs v1.1.0
yo v1.4.5
osx 10.10.2

but it does find global packages when it is installed locally or i use nvm to switch to node v0.10.36

**Comment by SBoudrias** [comment]
what is the NODE_PATH value when running iojs?

**Comment by oriSomething** [comment]
it's not set (empty).

wow, thanks for the fast reply

**Comment by SBoudrias** [comment]
Try running `yo doctor` while you're in iojs mode.

Otherwise, if you can find out where global packages are installed with iojs and making sure `yo` is installed there too. It might be the case yo is installed in a node version global npm folder and just work because of a PATH you set up somewhere else in your bash profiles.

**Comment by oriSomething** [comment]
![doctor](https://cloud.githubusercontent.com/assets/2685242/6050914/3b50b3d4-accc-11e4-84a3-7958e0ca4b38.png)

they've also seems to be installed on the same folder. i've tried to uninstall and install again, but also didn't help. also, i might not fully understand you

**Comment by pzuraq** [comment]
I'm having the same problem, yo is installed in iojs and everything appears to be working correctly aside from this.

**Comment by SBoudrias** [comment]
Might be related to https://github.com/yeoman/environment/issues/30

**Comment by SBoudrias** [comment]
This is now fixed, please update `yo` (`npm -g update`)
