### ISSUE TITLE
Unmet Peer Dependency Warnings on Several Generators

### ISSUE THREAD

**Issue by damienstanton** [yeoman/yo#373]
`yo` does not appear to be reporting as a peer properly, in any generators I have tested. I am using OS X 10.11, node 4.2.1 and npm 3.3.9.

Output of two of my tests, one with `generator-bangular` and another with `generator-gulp-angular`:
```bash
 work_folder  》 npm install -g generator-gulp-angular
/usr/local/lib
├── generator-gulp-angular@1.0.0
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-gulp-angular@1.0.0 requires a peer of yo@>=1.0.0 but none was installed.
 work_folder  》 npm install -g generator-bangular
/usr/local/lib
├── generator-bangular@0.11.3
└── UNMET PEER DEPENDENCY yo@>=1.4.0

npm WARN EPEERINVALID generator-bangular@0.11.3 requires a peer of yo@>=1.4.0 but none was installed.
```
However...
```bash
 work_folder  》 npm -g list | grep yo
│ └─┬ yosay@1.0.5
└─┬ yo@1.4.8
  └─┬ yosay@1.0.5
```

This is a major problem as these generators (and untold more) are effectively broken unless they remove `yo` as a peer dependency.

**Comment by eddiemonge** [comment]
It works for me. Maybe try removing all your global packages and reinstalling them (or at least `yo`)?

**Comment by SBoudrias** [comment]
> This is a major problem as these generators (and untold more) are effectively broken unless they remove yo as a peer dependency.

Peer dependency is not enforced by npm. Worse thing that'll happen is people will get a warning in their console.

Also, yo doesn't handle installation or what dependencies a generator define. There's nothing we can do on our side about these warnings.

**Comment by joshkpeterson** [comment]
I keep seeing people say in different issue threads that "this is only a warning," however, this prevents generators from being installed on my machine.

The fix is to install yo in the same command like so:
`npm install -g yo generator-webapp`

I realize this is perhaps technically an issue with npm, but there are a ton of threads in google search results with a bunch of really messy supposed fixes involving wiping npm things and reinstalling. Above is the only thing that works for me, so spreading this info around.
