### ISSUE TITLE
Can not select anything after running `yo` within cmd.exe

### ISSUE THREAD

**Issue by julmot** [yeoman/yo#408]
When running `yo` you can normally choose what to do with down and up arrows. However, for me this doesn't work within cmd.exe. I'm running NodeJS 4.2.2 and Yo 1.6.0.
In another shell like [ConEmu](https://github.com/Maximus5/ConEmu) this does work.
![2016-02-06_231329](https://cloud.githubusercontent.com/assets/8310677/12869711/74ffc486-cd27-11e5-8301-920c52426784.png)
I can confirm that this is not a problem of Inquirer.js as generators with it are working.

**Comment by SBoudrias** [comment]
Update Node and retry.

**Comment by julmot** [comment]
Worked with 5.5.0. You might add a note about the required NodeJS version in the documentation.

**Comment by thasmo** [comment]
@SBoudrias, this happens also to me using `cmd.exe` on the latest Node 5.10.1, although sometimes it works. If it does, I can finish the `prompting` but atfer that it still hangs. I've already uninstalled `yo`, and re-installed it with an empty npm cache; no luck.

**Comment by SBoudrias** [comment]
There was a regression in Node and the bug started happening again. See nodejs/node#5384 and nodejs/node#5927

For now, for most user it looks like accessing yo from the initial `yo` (then select your generator) command will work just fine.

**Comment by jokeyrhyme** [comment]
I have a module that helps identify broken versions of Node:

- https://github.com/jokeyrhyme/is-node-interactive-tty-broken

Do you think it might be worth integrating a similar check into this library? So that a warning or something could be displayed? Or perhaps modifying the "engines" part of package.json to help avoid broken Node versions at installation time?
