### ISSUE TITLE
Arrow keys do not work

### ISSUE THREAD

**Issue by vitaly-t** [yeoman/yo#424]
I'm using Node.js 5.10 under Windows 10 (64-bit), and the arrow keys do not work.

Switching to Node.js 0.12.13 makes the arrows keys work again.

**Comment by sindresorhus** [comment]
This is a Node.js issue. See: https://github.com/SBoudrias/Inquirer.js/issues/303 and https://github.com/nodejs/node/issues/5384

**Comment by jokeyrhyme** [comment]
If this is related to https://github.com/nodejs/node/issues/5384 then I have a module that helps identify broken versions of Node:

- https://github.com/jokeyrhyme/is-node-interactive-tty-broken

Do you think it might be worth integrating a similar check into this library? So that a warning or something could be displayed? Or perhaps modifying the "engines" part of package.json to help avoid broken Node versions at installation time?
