### ISSUE TITLE
Problem with tabtab while installing yo@1.8.1

### ISSUE THREAD

**Issue by Bartlomiejsz** [yeoman/yo#430]
While installing latest version of yo i got following errors in cli:

```
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppDa
ta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browserify
" "generator-base-reactjs" "yo"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! yo@1.8.1 postinstall: `yodoctor && npm run tabtab`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yo@1.8.1 postinstall script 'yodoctor && npm run tabtab'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor && npm run tabtab
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.
```

Do you know what is the reason?
Node version: **6.0.0**
npm version: **3.8.9**

**Comment by mklabs** [comment]
@Bartlomiejsz Thank you for reporting this. It's because of the completion feature which was recently added and released with yo@1.8.0 Windows is unfortunately not supported and tabtab reports it loudly.

@SBoudrias Just published tabtab@1.3.2 which includes a fix to bypass installation on Windows and other non-supported shells.

@Bartlomiejsz Can you confirm the installation goes through without errors now ? You should automatically get latest tabtab version since it's tagged with `^1.3.0`

**Comment by Bartlomiejsz** [comment]
@mklabs Thank you, right now installation is completed succesfully.

**Comment by williamboman** [comment]
To piggyback on this issue, would it be possible to cache the answer given to tabtab? It's a bit annoying seeing my daily system update script halting whenever yo (or any other module that uses tabtab) releases a new version.

**Comment by mklabs** [comment]
@Bartlomiejsz Cool! Thanks again.

@williamboman Interesting idea. It should be possible.

**Comment by severus-ebay** [comment]
I am new to yeoman, in fact I am trying to install it for the first time and I get stuck in the installation:
here is what I did following the setup guide:
- I just installed  Node.js (version v4.4.4), npm (version3.9.0) and git (version 2.8.1.windows.1)
- I ran this command in the directory of my project:
    npm install --global yo bower grunt-cli
and all I have got is a message stating:

Everything looks all right!
>yo@1.8.1 tabtab C: Users\rra\AddData\Roaming\npm\node_modules\yo
>[ $CI ] || tabtab install --name=yo --completer=yo-complete

tabtab:commands Windows shell completion not yet supported, skipping completion install

I have read the same problem here: https://github.com/yeoman/yo/issues/430
and the answer from @mklabs is:  
"Just published tabtab@1.3.2 which includes a fix to bypass installation on Windows and other non-supported shells."

But as I said since I am new on this topic I do not get "where" to find this tabtab@1.3.2 to download.

Any help would be appreciated

Thanks

**Comment by SBoudrias** [comment]
@severus-ebay can you copy paste the error you're having?

You don't need to manually install the new tabtab version, that's done automatically.

**Comment by severus-ebay** [comment]
@SBoudrias here you have an screenshot about the whole thing.

Sorry that is in German language. Essentially after it says: Everything looks all right! it continues telling:

> yo@1.8.1 tabtab C: Users\rra\AddData\Roaming\npm\node_modules\yo
> [ $CI ] || tabtab install --name=yo --completer=yo-complete
> 
> The command "[" is written either incorrect or could not be found.
> tabtab:commands Windows shell completion not yet supported, skipping completion install

I have tried to install it in two different computers (at work and at home) and I have got the same error.

![yoman](https://cloud.githubusercontent.com/assets/1099412/15336120/43b649a2-1c75-11e6-8ffb-f628575d7c00.JPG)

**Comment by SBoudrias** [comment]
@mklabs is tabtab ready for yeoman to remove the `[ $CI ]` part of the package.json?

**Comment by mklabs** [comment]
@SBoudrias I'm working currently on a PR to move the completion script installation and prompts behind `yo completion`, this should remove the need to rely on this `[ $CI ]` variable.

**Comment by severus-ebay** [comment]
Hi there,
What does it means Yo completion #436?

I have tested again and I see not success, Yeomann is having problem with the tabtab and stops

Is it completed the update or are you working on it?

**Comment by SBoudrias** [comment]
Should be fixed now.
