### ISSUE TITLE
Can't install 1.8.2

### ISSUE THREAD

**Issue by jaumard** [yeoman/yo#437]
When I try `npm i -g yo` : 
node v4.4.4 (also try with 4.3.1)
npm  v3.9.0

```
deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo@1.8.2"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.0
npm ERR! path /usr/local/lib/node_modules/yo/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/yo/lib/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/yo/lib/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jaumard/Downloads/testTrails/npm-debug.log
```

If I install `npm i -g yo@1.8.1` all is working

**Comment by brbsix** [comment]
I couldn't get yo 1.8.2 to install on node v6.2.0 either.

**Comment by nmaggioni** [comment]
Seconding this, can't get it to install.

**Comment by shian48263** [comment]
Same error happening to me, node v6.2.0 & npm 3.8.9.

**Comment by bezoerb** [comment]
@SBoudrias Maybe this relates to https://github.com/npm/npm/issues/5082
I ran into the same issue after publishing a module with node 6. Switching back to node 5 & publish a patch version fixed the problem for me

**Comment by ddamw** [comment]
The same happened here on node 6.2.0, 6.0.0, 4.2.1 and 0.12.7, npm 2.14.7, 3.8.9 and 3.9.0
Some old versions indeed, but installing yo 1.8.1 worked without problem. 

I'm guessing the yo 1.8.2 package is missing some files and a hotfix will be released shortly.

**Comment by joelchu** [comment]
Same problem here with Mac El Captain with Node 4.4.4

37729 error Darwin 15.5.0
37730 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "yo" "--global"
37731 error node v4.4.4
37732 error npm  v2.15.1
37733 error path /usr/local/lib/node_modules/yo/lib/cli.js
37734 error code ENOENT
37735 error errno -2
37736 error syscall chmod
37737 error enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/yo/lib/cli.js'
37737 error enoent This is most likely not a problem with npm itself
37737 error enoent and is related to npm not being able to find a file.
37738 verbose exit [ -2, true ]
37739 verbose unbuild lib/node_modules/yo
37740 info preuninstall yo@1.8.2
37741 info uninstall yo@1.8.2
37742 verbose unbuild rmStuff yo@1.8.2 from /usr/local/lib/node_modules
37743 silly gentlyRm /usr/local/bin/yo is being gently removed
37744 silly gentlyRm verifying /usr/local is an npm working directory
37745 silly gentlyRm /usr/local/bin/yo-complete is being gently removed
37746 silly gentlyRm verifying /usr/local is an npm working directory
37747 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
37748 silly gentlyRm deletion target /usr/local/bin/yo is under /usr/local
37749 verbose gentlyRm vacuuming from /usr/local/bin/yo up to /usr/local
37750 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
37751 silly gentlyRm deletion target /usr/local/bin/yo-complete is under /usr/local
37752 verbose gentlyRm vacuuming from /usr/local/bin/yo-complete up to /usr/local
37753 info postuninstall yo@1.8.2
37754 silly gentlyRm /usr/local/lib/node_modules/yo is being purged from base /usr/local
37755 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/yo
37756 silly vacuum-fs purging /usr/local/lib/node_modules/yo
37757 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules

**Comment by superclarkk** [comment]
Same problem on:

~~~
Ubuntu 12.04
3.2.0-91-generic
node v5.9.0
npm 3.9.0
~~~

**Comment by drakoumel** [comment]
same issue here.

**Comment by clarkd** [comment]
Same here on Windows with node 6.2.0 and npm 3.9.2

**Comment by Mohamed-Abo-El-Soud** [comment]
same issue here

**Comment by gauravbansal74** [comment]
Same issue. +1

**Comment by Eqistyre** [comment]
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/yo/lib/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/yo/lib/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Eqistyre/npm-debug.log

same issue from mac osx

**Comment by otorcatf** [comment]
Same issue here on Windows 10 with Node 4.4.4 and npm 3.9.0

**Comment by yanyu0517** [comment]
same issue with node 4.2.2 and npm 2.14.7

**Comment by murtuzasyed** [comment]
same issue with 1.8.2

**Comment by philipobrien** [comment]
Same issue with node 6.2.0

**Comment by viktorbijlenga** [comment]
Same issue here! I installed the previous version of yo - 1.8.1 as a temporary work around.
`npm install -g yo@1.8.1`

**Comment by squalsoft** [comment]
same issue:
MacbookBlack:~ didiandmalish$ sudo npm i -g yo
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "i" "-g" "yo"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /usr/local/lib/node_modules/yo/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/yo/lib/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/yo/lib/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/didiandmalish/npm-debug.log

**Comment by interneth3ro** [comment]
This really needs to be fixed ASAP. I'm at a standstill on a project with a brand new client and cannot do ANYTHING because "npm install" fails due to this error.

**Comment by parvbhullar** [comment]
Same issue here on El Cap. even 1.8.1 is not working, once its installed yo command not found when try to install generators.

**Comment by shian48263** [comment]
@interneth3ro: If you're in a hurry, why don't try changing yeoman version to 1.8.1 in package.json.

**Comment by interneth3ro** [comment]
@shian48263 I did install 1.8.1 globally, but somewhere deep in my dependency chain is likely a reference to the latest version (or rather, no reference to a version, hence grabbing the latest one). And I really don't fancy digging through every single package.json for every single dependency trying to find it.

**Comment by parvbhullar** [comment]
@shian48263 same here what @interneth3ro is facing. :(

**Comment by SBoudrias** [comment]
# Fixed

```
npm -g install yo@1.8.3
```

Not sure what happened, looks like npm published a corrupted package.

**Comment by interneth3ro** [comment]
Excellent, working again on my end. Many thanks for the quick fix!

**Comment by kevva** [comment]
Might have to do something with https://github.com/SamVerschueren/npm-publish-index-test.

**Comment by gauravbansal74** [comment]
@SBoudrias thank you . Its working fine now :) :) 👍

**Comment by deepu105** [comment]
:+1:
