### ISSUE TITLE
Install yo is failing at yeoman doctor sanity check

### ISSUE THREAD

**Issue by emailtosamit** [yeoman/yo#626]
## Type of issue

Bug

## My environment

* *OS version/details*: Windows 7 enterprise
* *Node version: v10.16.0
* *npm version:* 6.9.0
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Expected behavior

I expect yo should be installed without any error using command npm install -g yo

## Current behavior

I am behind corporate proxy at work. The yo installation succeed but failing at Yeoman Doctor sanity check step. 

## Steps to reproduce the behavior

Run command npm install -g yo

## Command line output

H:\>npm install -g yo
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a bu
ild toolchain, use it instead
C:\Users\samit\AppData\Roaming\npm\yo-complete -> C:\Users\samit\AppData\Roa
ming\npm\node_modules\yo\lib\completion\index.js
C:\Users\samit\AppData\Roaming\npm\yo -> C:\Users\samit\AppData\Roaming\npm\
node_modules\yo\lib\cli.js

> yo@3.1.0 postinstall C:\Users\samit\AppData\Roaming\npm\node_modules\yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

V No .bowerrc file in home directory
V Global configuration file is valid
V NODE_PATH matches the npm root
V No .yo-rc.json file in home directory
V Node.js version
{ RequestError: connect ETIMEDOUT 104.16.20.35:80
    at ClientRequest.req.once.err (C:\Users\samit\AppData\Roaming\npm\node_mod
ules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.16.20.35:80',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
× yo version
{ RequestError: connect ETIMEDOUT 104.16.20.35:80
    at ClientRequest.req.once.err (C:\Users\samit\AppData\Roaming\npm\node_mod
ules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.16.20.35:80',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
V npm version

Found potential issues on your machine :(
+ yo@3.1.0
updated 6 packages in 401.195s

**Comment by emailtosamit** [comment]
Please note i already checked other bug "https://github.com/yeoman/yo/issues/589" but can't find solution of issue mention in this bug.

**Comment by SBoudrias** [comment]
Are you behind a proxy?

**Comment by emailtosamit** [comment]
Yes, I am behind corporate proxy at work. The yo installation succeed but failing at Yeoman Doctor sanity check step.

**Comment by SBoudrias** [comment]
Yeah that's because it's checking to see if there's newer versions; but looks like your proxy is blocking the network call.

The failure is only a warning, so `yo` should still be usable. I'll close as we can't really help you debug your proxy configuration.

**Comment by emailtosamit** [comment]
The installation of gulp succeed means the proxy is allowing to install package. Yo also installed but failed at Sanity check. Are you saying the Yo sanity check reach network differently compare to other npm module. 

I verified below command is also failing may be related to Sanity check

yo @microsoft/sharepoint

**Comment by SBoudrias** [comment]
The sanity check only prints warnings about potential issues on your system - it's not blocking anything.

But indeed `npm` might use the network differently than how node modules will. So other node modules making network calls; like `@microsoft/generator-sharepoint` might run into the same issue. But that's not caused by Yeoman, that's due to your proxy configuration.

**Comment by bioshazard** [comment]
The assumption that the proxy is at fault is a disservice. I can see in my case that `lsof -p $PID_OF_YO_DOCTOR` that it is timing out on a direct TCP connection to `104.16.20.35:https (SYN_SENT)`. I would not be surprised if @emailtosamit was able to see this result as well. I found `npx yo doctor` works, but that does not help me with my existing build process. No combination of `anything_proxy=$myproxy` or any `npm config set proxy` has helped me.

**Comment by bioshazard** [comment]
It is dangerous to assume the proxy is at fault here. I can see in my case that `lsof -p $PID_OF_YO_DOCTOR` that it is timing out on a direct TCP connection to `104.16.20.35:https (SYN_SENT)` rather than my proxy which works in all other cases. I would not be surprised if @emailtosamit was able to see this result as well. I found `npx yo doctor` works, but that does not help me with my existing build process. No combination of `anything_proxy=$myproxy` or any `npm config set proxy` has helped me.

> it's not blocking anything.

There is a very real harm to build lead time. If there was a way to skip waiting for this impossible remote call to time out, maybe it would not be such a big problem.

**Comment by MXGackowski** [comment]
I have similar problem, but its weird because its no any error messages

`user@machine:~/workspace$ npm install yo
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead

> yo@4.2.0 postinstall workspace/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

+ No .bowerrc file in home directory
+ Global configuration file is valid
+ NODE_PATH matches the npm root
+ No .yo-rc.json file in home directory
+ Node.js version
+ npm version`

and then I waits infinite...

Anyone have an idea what is wrong?
